name: Update Changelog

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
          outputFile: "TEMP_CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        run: |
          VERSION="${{ github.event.release.tag_name || github.event.inputs.version }}"
          DATE=$(date +%Y-%m-%d)
          
          # Create new changelog entry
          echo "## [$VERSION] - $DATE" > NEW_ENTRY.md
          echo "" >> NEW_ENTRY.md
          cat TEMP_CHANGELOG.md >> NEW_ENTRY.md
          echo "" >> NEW_ENTRY.md
          
          # Insert new entry after [Unreleased] section
          sed -i '/## \[Unreleased\]/r NEW_ENTRY.md' CHANGELOG.md
          
          # Clean up temp files
          rm TEMP_CHANGELOG.md NEW_ENTRY.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update changelog for ${{ github.event.release.tag_name || github.event.inputs.version }}"
          title: "Update changelog for ${{ github.event.release.tag_name || github.event.inputs.version }}"
          body: |
            This PR updates the changelog for version ${{ github.event.release.tag_name || github.event.inputs.version }}.
            
            Changes are automatically generated based on merged PRs since the last release.
          branch: update-changelog-${{ github.event.release.tag_name || github.event.inputs.version }}
          base: main
          labels: |
            documentation
            automated pr